### ISSUE TITLE
Suggestion (Not an Issue)

### ISSUE THREAD

**Issue by JamesJackson123** [paulmaunders/delivery-slot-bot#19]
Could it be possible to have a feature where in conjunction to  sending a ping to your phone it makes a noise or sends an alert to the PC just to make sure you 100% know slots are free as they usually are gone within 10 minutes.

**Comment by aaparmeggiani** [comment]
Hehe .. on a Mac, you could make a system  call:   `say  "Quick!  I've found a slot!!" `

**Comment by CharlesButcher** [comment]
This would be very helpful. I think the following works for the Mac `say` command, but I don't know how to hook it in to the rest of the code, and Git flummoxes me. I'm thinking it could go in a file called `/notifications/MacSpeak.js`, called from `tesco.js` and with a switch in the config file?

```
var myAlert = "Alert! Alert! Alert! We have a delivery slot!";
var exec = require('child_process').exec, child;
exec('say ' + myAlert,
    function (error, stdout, stderr) {
        console.log('stdout: ' + stdout);
        console.log('stderr: ' + stderr);
        if (error !== null) {
             console.log('exec error: ' + error);
        }
    });
```

**Comment by andytson** [comment]
I've done this as another notifier called at the same time as the pushover notification send https://github.com/paulmaunders/delivery-slot-bot/pull/26

**Comment by CharlesButcher** [comment]
Thank you!

**Comment by aaparmeggiani** [comment]
Just wondering,  when running through Docker,  it will not work even on a Mac.  Wouldn't  be the case of using `play-sound` library  to output an alert.mp3 ?? 

Another idea would be pushing a "Start" message when firing the app, so that it automatically tests if the pushover / speakers are working fine ;-)

**Comment by CharlesButcher** [comment]
With these slots so scarce (no hits for me so far) it's certainly worth making sure we don't miss any. So yes, a great idea to test the whole alert system on startup.

I'm impressed with Pushover but currently struggling to see how to get it to play sound alerts overnight, when my (Android) phone is on do not disturb. I don't really want to turn off DND, and I don't want to stop notifications from other apps during the day.

**Comment by CharlesButcher** [comment]
Just got my first alert. Thank you team! Worked like a charm. Five days' worth of slots gone in 15 minutes.

Minor point to fix: the `type` variable didn't work:

> const myAlert = `Alert! Alert! Alert! We have ${type}!`;

I forget what the Mac said after "We have", but it wasn't "Tesco delivery slots".

**Comment by andytson** [comment]
@CharlesButcher congrats. I've fixed that issue now https://github.com/paulmaunders/delivery-slot-bot/pull/29

**Comment by CharlesButcher** [comment]
Success today finding another slot. Thanks, guys! In truth it wasn't all that hard (my local had slots tomorrow and for most of next week), but that's not the bot's fault ;-) The Mac spoken announcement is really something.
