### ISSUE TITLE
Slot Availaible Ping but no slot in actual

### ISSUE THREAD

**Issue by RishiChopra** [paulmaunders/delivery-slot-bot#20]
Hi,

I have seen it multiple times that a slot notification is sent but when i login 10 second later no slot is there. Could you let me know how can that happen? or i am missing something?

Regards
Rishi

**Comment by paulmaunders** [comment]
This happens to me too, although I'm not exactly sure why. 

It seems that sometimes the slots only appear for a couple of minutes, but other times they do stick around for longer and I have been able to book a delivery earlier this week.

**Comment by RishiChopra** [comment]
I tried to perform a check on tesco.com immediately within 10 seconds and seems like it disappears everytime.
No success in last 15 attempts :(

Not sure why though

**Comment by aaparmeggiani** [comment]
Had mine at around 5pm the other day.  1st time, polling every 5min, I was too late to get one.  2nd time, polling every 2min, and with the browser already logged in, I managed to see slots on the whole saturday after receiving the notification.  It didn't last another minute though .. after refreshing the page, everything was gone.

**Comment by paulmaunders** [comment]
They go like hot cakes!
