### ISSUE TITLE
Server memory - for info

### ISSUE THREAD

**Issue by robertf2001** [paulmaunders/delivery-slot-bot#22]
Hi,
Really nice utility.

Just to help others, I attempted to run the "Docker" version on a Free Tier Google Computer VM (Container-OS, f1-micro (1 vCPU, 0.6 GB memory). 
Routine appears to fail when trying to login to Tesco site with a Timeout issue.

Changed to use a machine type (n1-standard-1 (1 vCPU, 3.75 GB memory) - works great!

**Comment by andytson** [comment]
I've been learning Rust a bit, which would definitely allow for very low memory requirements, but obv with a steep learning curve for others to contribute

**Comment by paulmaunders** [comment]
Thanks for the info and glad to hear you have found it useful. We could certainly make it more efficient if we didn't use puppeteer (and therefore chrome) but it would be more tricky to code. Given the speed we wanted to deploy the script, puppeteer is really flexible and easy to work with!

**Comment by johnpilbeam** [comment]
I have this running on a $5 a month Digital Ocean Droplet ([https://marketplace.digitalocean.com/apps/docker](https://marketplace.digitalocean.com/apps/docker)) with no issues. Slight cost (but less than most Tesco slots), very simple to set up and no issues so far.
