### ISSUE TITLE
Pushover test

### ISSUE THREAD

**Issue by smorrel1** [paulmaunders/delivery-slot-bot#25]
In case it helps anyone; I managed to bungle the Pushover config and missed some slots. Grr. You can test Pushover with:
`cp delivery-slots.js delivery-slots-test.js`
`vi delivery-slots-test.js`
then change lines 53 to 55 from:
`if (html.includes("No slots available! Try another day")) {`
 `       console.log("No slots");`
`      } else {`
to:
`      if (1) {`
``
``
Then run it with 
`node delivery-slots-test.js >> ~/git/delivery-slot-bot/cron.test.log 2>&1`
and you should get a Pushover notification :) if not, check your configs.

**Comment by andytson** [comment]
note you can do instead:
```
node test-push.js
```

**Comment by MrDibbley** [comment]
how do you run the node test-push.js in docker land? i have run docker-compose up and all seems to be working fine, just needed to check the notifications 

Thanks

**Comment by andytson** [comment]
you can do it either in the running container as:
```
docker-compose exec app node test-push.js
```
Or if it's not running:
```
docker-compose run --rm app node test-push.js
```

**Comment by MrDibbley** [comment]
Thanks works a treat, every little helps :)

**Comment by deanpm70** [comment]
I get the following error when trying to running "node test-push.js"

~/delivery-slot-bot$ node test-push.js
/xxxx/xxxx/delivery-slot-bot/test-push.js:5
config.notifiers.forEach((notifier) => notifier.sendMessage("Test message"));
                 ^

TypeError: Cannot read property 'forEach' of undefined
    at Object.<anonymous> (/home/dean/delivery-slot-bot/test-push.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

A cursory examination of the code suggests that if pushover_api_token is set in config.ini a new notifier will be pushed into notifiers. Both pushover_api_token and pushover_notification_users[] are set appropriately in my config.ini.

**Comment by andytson** [comment]
fixed
