### ISSUE TITLE
Adding Group4 slots

### ISSUE THREAD

**Issue by NigelRSB** [paulmaunders/delivery-slot-bot#30]
Paul:
Just brilliant! Thank you so much.
I'm not sure whether it is the same for all regions, but once logged in and at https://www.tesco.com/groceries/en-GB/slots/delivery, in our area there are two types of delivery slot: 1 hr and 4 hr delivery windows with buttons to toggle between the same week-tabheaders. Redirecting from the login page it seems to default to the Group1 slots (1 hr delivery window), and that bit is working really well,  but I am struggling to understand how to scrape the Group4 slots as well. Any thoughts, please?
Many thanks.

**Comment by paulmaunders** [comment]
Hi Nigel, Thanks for your kind words! I don't have that option in my region so it's hard to test. Assuming they load up different URLs it would be a case of figuring out the pattern for those URLs in the HTML so the script could match them and loop through them. If you can paste some example HTML here for that section we may be able to suggest some changes for you to try...

**Comment by CharlesButcher** [comment]
This is hard to do when there are no slots! But the form of the URL is almost identical to that for the 1-hour slots:

https://www.tesco.com/groceries/en-GB/slots/delivery/2020-04-09?slotGroup=4

So we might hope the resulting HTML would be pretty similar.

**Comment by woodsie6** [comment]
I don't think there is a huge need for the 4-hour slot functionality - when a slot opens up it appears in both categories. The difference is in price only, i.e. a 4-hour slot is cheaper by a pound or so to give Tesco the flexibility. I'd quite happily pay the extra quid to snare a delivery slot at this point! A more valuable addition at this point would be to grab a slot once found but will leave that to @paulmaunders  and @andytson - wizards! Have a good Easter.
