### ISSUE TITLE
Asda?

### ISSUE THREAD

**Issue by JamesJackson123** [paulmaunders/delivery-slot-bot#31]
Is it possible to add asda to the delivery slot bot as an option? 

Asda releases slots randomly throughout the day when they become available in the area so the bot being able to ping us when the slots are released would be wonderful.

https://groceries.asda.com/checkout/book-slot?tab=deliver&origin=/

**Comment by sansfont** [comment]
I couldn't work out how to get info from the slot booking page myself, but if you do get round to adding Asda this might come in useful.

Modifying `src/stores/tesco.js` to use
```js
const deliveryUrl = "https://groceries.asda.com/checkout/book-slot?tab=deliver";
const collectionUrl = "https://groceries.asda.com/checkout/book-slot?tab=collect";
const loginUrl = "https://www.asda.com/login";
```
you can log into Asda's site and redirect to the relevant Url with
```js
async login(page, url) {
    console.log("Logging in with new Asda session");

    // go directly to login, giving redirect uri in params
    await goto(page, `${loginUrl}?redirect_uri=${url}`);
    await page.type("input[type='text']", this.username);
    await page.type("input[type='password']", this.password);
    await page.keyboard.press(String.fromCharCode(13)); // Press the return key
    await page.waitForNavigation();
    await assertLoginSuccess(page);

    // keep cookies for next run
    this.cookieStore.set(await page.cookies());
  }
```

**Comment by paulmaunders** [comment]
ASDA has now been added so closing this issue.
