### ISSUE TITLE
latest build issue with fsevents on linux? still seems to run ok

### ISSUE THREAD

**Issue by MrDibbley** [paulmaunders/delivery-slot-bot#40]
yarn install v1.22.0

output from app log:

[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 16.27s.

**Comment by andytson** [comment]
It can be ignored. Not much we can do to avoid the message until the main installation method is from npm repository

**Comment by MrDibbley** [comment]
Cool thanks
