### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by flashcash** [paulmaunders/delivery-slot-bot#49]
Hi, do you know how to fix this error :-

1587316783537 Sun, 19 Apr 2020 17:19:43 GMT
Logging in with new user session
Opening https://groceries.asda.com/checkout/book-slot?tab=deliver
No slots
Already logged in
Opening https://groceries.asda.com/checkout/book-slot?tab=collect
**Cannot read property 'supported_timezone' of null**

**Comment by andytson** [comment]
Fixed in the PR merged mentioned above
