### ISSUE TITLE
Unable to clone using git? Please help

### ISSUE THREAD

**Issue by HennahS-ALTOUR** [paulmaunders/delivery-slot-bot#5]
> git clone git@github.com:paulmaunders/delivery-slot-bot.git
git clone git@github.com:paulmaunders/delivery-slot-bot.git
    ^^^^^

Uncaught SyntaxError: Unexpected identifier
> cd delivery-slot-bot
cd delivery-slot-bot
   ^^^^^^^^

Uncaught SyntaxError: Unexpected identifier
> npm install yarn -g
npm should be run outside of the node repl, in your normal shell.
(Press Control-D to exit.)
> yarn installgit clone git@github.com:paulmaunders/delivery-slot-bot.git
yarn installgit clone git@github.com:paulmaunders/delivery-slot-bot.git
     ^^^^^^^^^^

**Comment by esticle** [comment]
```
$ git clone https://github.com/paulmaunders/delivery-slot-bot
$ cd delivery-slot-bot
$ npm install yarn -g

```

**Comment by HennahS-ALTOUR** [comment]
Hi, this still does not work.. Please can you advise? Sorry I've never worked with JS before. 

```
> cd delivery-slot-bot
cd delivery-slot-botthub.com/paulmaunders/delivery-slot-bot
   ^^^^^^^^

Uncaught SyntaxError: Unexpected identifier
> npm install yarn -g
npm should be run outside of the node repl, in your normal shell.
(Press Control-D to exit.)
>                                          
```

**Comment by paulmaunders** [comment]
Are you running this in a terminal shell?

**Comment by HennahS-ALTOUR** [comment]
I'm executing that code in Node.js

It looks like cmd or terminal..

**Comment by paulmaunders** [comment]
You need to run this code inside the terminal directly, not inside node.js

Assuming you are on a Mac:

- Open up a terminal window (Applications > Utilities > Terminal or Spotlight search for 'terminal')
- Change into the folder where you want to install the code, e..g `cd ~/Documents`
- Run the commands listed above.

**Comment by HennahS-ALTOUR** [comment]
Hi, thank you for helping me! 

npm is doing something I do not understand.. I have just completed the 1st step. 
```

npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules'] {
npm ERR!   stack: "Error: EACCES: permission denied, access '/usr/local/lib/node_modules'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

```

**Comment by HennahS-ALTOUR** [comment]
Hi, thank you for helping me! I still have an issue. Would you be able to advise please?

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/config.ini.example - Not found
npm ERR! 404 
npm ERR! 404  'config.ini.example@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hennahsahonte/.npm/_logs/2020-03-31T13_02_08_210Z-debug.log
Hennahs-MacBook:delivery-slot-bot hennahsahonte$ vim config.ini
```

**Comment by esticle** [comment]
Check the README.md file:

```
cp config.ini.example config.ini
vim config.ini
```

Once the config.ini is in place you should be able to npm run it.
