### ISSUE TITLE
input.on

### ISSUE THREAD

**Issue by darrenbyers** [paulmaunders/delivery-slot-bot#53]
Sorry, bit of a noob.  Struggling to get this working.  Might be good to know which is the best OS to run?  I'm trying to build a VM specifically to get this working.

Anyway, seeing the following:

`$ node ./src/index.js
index.js

Runs one-off

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]

TypeError: input.on is not a function
    at new Interface (readline.js:207:11)
    at Object.createInterface (readline.js:75:10)
    at Promise (/root/delivery-slot-bot/node_modules/puppeteer/lib/Launcher.js:333:25)
    at new Promise (<anonymous>)
    at waitForWSEndpoint (/root/delivery-slot-bot/node_modules/puppeteer/lib/Launcher.js:332:10)
    at Launcher.launch (/root/delivery-slot-bot/node_modules/puppeteer/lib/Launcher.js:176:41)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

**Comment by paulmaunders** [comment]
Have you already run ```yarn install``` from inside the project folder?

**Comment by darrenbyers** [comment]
I had, yes.  I took a snapshot of the VM before I started, so I reverted and tried again.  I'm logged in as a normal user, not root, the only time I got a message about privs was when I ran npm install yarn -g.  Full listing below.  I think I need some prerequisites?

> [darren@linux ~]$ pwd
/home/darren
[darren@linux ~]$ ls
Desktop  Documents  Downloads  Music  Pictures  Public  Templates  Videos
[darren@linux ~]$ git clone https://github.com/paulmaunders/delivery-slot-bot.git
Cloning into 'delivery-slot-bot'...
remote: Enumerating objects: 46, done.
remote: Counting objects: 100% (46/46), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 369 (delta 25), reused 19 (delta 11), pack-reused 323
Receiving objects: 100% (369/369), 262.84 KiB | 964.00 KiB/s, done.
Resolving deltas: 100% (202/202), done.
[darren@linux ~]$ cd delivery-slot-bot/
[darren@linux delivery-slot-bot]$ npm install yarn -g
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/yarn
npm WARN checkPermissions Missing write access to /usr/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/lib/node_modules/yarn
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules/yarn'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/lib/node_modules/yarn']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/usr/lib/node_modules/yarn\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules/yarn' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/darren/.npm/_logs/2020-04-20T22_33_41_192Z-debug.log
[darren@linux delivery-slot-bot]$ sudo npm install yarn -g

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for darren:
/usr/bin/yarn -> /usr/lib/node_modules/yarn/bin/yarn.js
/usr/bin/yarnpkg -> /usr/lib/node_modules/yarn/bin/yarn.js
+ yarn@1.22.4
updated 1 package in 0.474s
[darren@linux delivery-slot-bot]$ yarn install
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 35.36s.
[darren@linux delivery-slot-bot]$ cp config.ini.example config.ini
[darren@linux delivery-slot-bot]$ vi config.ini
[darren@linux delivery-slot-bot]$ yarn start
yarn run v1.22.4
$ node ./src/index.js
index.js

Runs one-off

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]

Error: Failed to launch chrome!
/home/darren/delivery-slot-bot/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/darren/delivery-slot-bot/node_modules/puppeteer/lib/Launcher.js:348:14)
    at Interface.helper.addEventListener (/home/darren/delivery-slot-bot/node_modules/puppeteer/lib/Launcher.js:337:50)
    at Interface.emit (events.js:203:15)
    at Interface.close (readline.js:397:8)
    at Socket.onend (readline.js:173:10)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[darren@linux delivery-slot-bot]$

**Comment by paulmaunders** [comment]
Which Linux distro are you using?

**Comment by paulmaunders** [comment]
Assuming it's Ubuntu, could you try adding the following dependencies? 

    sudo apt-get install gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget

**Comment by darrenbyers** [comment]
I think I'm fighting a losing battle here.  I've tried it on Raspbian, CentOS and now Ubuntu and keep hitting the same issues relating to modules not being found.  I've been using Linux systems professionally since 1996 but obviously not to the depths required for this.  I still consider myself a noob!  Might be easier if I code something in a language I know.  I'm grateful for your time to try and get me up and running though.

**Comment by kchowdhree** [comment]
If it works one-off then you could instead just put it into Linux cron on a 5 minutely schedule?

To get puppeteer working in Windows Subsystem for Linux running Ubuntu 18 I had to make a few changes to the sandbox settings but otherwise all good. 

Great set of scripts!

**Comment by darrenbyers** [comment]
Thanks, I can't even get it to work once.  It's not the scripts fault.  I am trying to build a new VM, I'm used to installing a variety of distributions but prefer CentOS.  It's been may years since I did any development in Linux, the last time was in the HP-UX days and that was only Shell Script and Perl!  I'm a little out of my depth here.

**Comment by paulmaunders** [comment]
OK I have just about managed to get it working on CentOS 7 - but it was a bit of a mission :) 

Double check all node modules are installed correctly....

    yarn install --check-files

Install all dependencies for chrome

    sudo yum install pango.x86_64 libXcomposite.x86_64 libXcursor.x86_64 libXdamage.x86_64 libXext.x86_64 libXi.x86_64 libXtst.x86_64 cups-libs.x86_64 libXScrnSaver.x86_64 libXrandr.x86_64 GConf2.x86_64 alsa-lib.x86_64 atk.x86_64 gtk3.x86_64 ipa-gothic-fonts xorg-x11-fonts-100dpi xorg-x11-fonts-75dpi xorg-x11-utils xorg-x11-fonts-cyrillic xorg-x11-fonts-Type1 xorg-x11-fonts-misc

Then this is the strange bit... you need to rename some files and change their permissions to get chrome sandboxing to work:

    cd /path-to/node_modules/puppeteer/.local-chromium/linux-XXXX/chrome-linux/
    mv chrome_sandbox chrome-sandbox
    chown root chrome-sandbox
    chmod 4755 chrome-sandbox

I found these instructions here: https://github.com/puppeteer/puppeteer/issues/391

**Comment by darrenbyers** [comment]
Amazing!  Thank you so much for going the extra mile to help me out Paul.  Nearly there.

I got Asda working fine, but Tesco is reporting auth failed.  I've tried two different accounts for Tesco.  Are there any logs generated?

> [root@localhost delivery-slot-bot]# yarn start
yarn run v1.22.4
$ node ./src/index.js
1587557717710 Wed, 22 Apr 2020 12:15:17 GMT
Logging in with new user session
error: Auth failed. Please check details are correct in config.ini
1587557719529 Wed, 22 Apr 2020 12:15:19 GMT
Logging in with new user session
Opening https://groceries.asda.com/checkout/book-slot?tab=deliver
No slots
Done in 6.67s.

**Comment by darrenbyers** [comment]
Scratch that, seems to be working now:
`[root@localhost delivery-slot-bot]# yarn start
yarn run v1.22.4
$ node ./src/index.js
1587558546117 Wed, 22 Apr 2020 12:29:06 GMT
Logging in with new user session
Opening https://www.tesco.com/groceries/en-GB/slots/delivery/2020-04-22?slotGroup=1 [Apr 22 - 28]
No slots
Opening https://www.tesco.com/groceries/en-GB/slots/delivery/2020-04-29?slotGroup=1 [Apr 29 - May 05]
No slots
Opening https://www.tesco.com/groceries/en-GB/slots/delivery/2020-05-06?slotGroup=1 [May 06 - 12]
No slots
1587558564154 Wed, 22 Apr 2020 12:29:24 GMT
Logging in with new user session
Opening https://groceries.asda.com/checkout/book-slot?tab=deliver
No slots
Done in 22.76s.
`

**Comment by paulmaunders** [comment]
Fantastic, glad I could help! 

I also had some intermittent login errors with it working on one of my servers and not another, but it also has started working again for me.
