### ISSUE TITLE
yarn start worked first time , but fails  with " error: Auth failed."  on subsequent tries

### ISSUE THREAD

**Issue by IanB999** [paulmaunders/delivery-slot-bot#55]
This is for  a tesco account

**Comment by IanB999** [comment]
No changes have been made to config.ini

**Comment by IanB999** [comment]
Works fine for  Asda credentials.

**Comment by flyfoxuk** [comment]
Ian - I'm getting this error too just now.  Did you resolve it?

**Comment by IanB999** [comment]
no ,   been trying different accounts  with no luck.

Either tesco is blocking  or  the code needs changing

**Comment by IanB999** [comment]
glad it's not just me  , appreciate the email
