### ISSUE TITLE
Only alert to slots available once per appearance

### ISSUE THREAD

**Issue by andytson** [paulmaunders/delivery-slot-bot#6]
In the event that slots are not taken within 5 minutes of an alert, another alert is sent for the same slots as they are available in the next scan.

Keeping the state of the previous scan slots can then be used to check for differences with the currently found slots to determine whether a new alert should be sent.

This would be easier to implement in the internal cron mode of my other PR without needing to maintain state outside of the application.

**Comment by paulmaunders** [comment]
We could skip the login step after the initial log in if running from the internal scheduler - this would reduce the load on their servers, and make the checks quicker.

**Comment by paulmaunders** [comment]
It might also help with the intermittency issue #8

**Comment by andytson** [comment]
sure, I was thinking that also, but will need to verify still logged in and re-login if not. Additionally the first page capturing the delivery date ranges is the first week as well, so can also reduce the number of calls there also
