### ISSUE TITLE
Not Output after yarn start

### ISSUE THREAD

**Issue by drakma5** [paulmaunders/delivery-slot-bot#60]
I struggled to get any output after yarn start, not sure if I am doing something wrong. Any help is appreciated

**Comment by GanydeBeilovsky** [comment]
Same issue. Stuck at 
`app_1     | yarn run v1.22.4`
for extended period with no output. Using Docker Toolbox on windows 10.

**Comment by RossBaptie** [comment]
Is this when you run as 'yarn start cron' ?

perhaps the setting in Cron is making it wait a while before running the first check?

In the config.ini file if you set it to run every 5 minutes 

`cron = '*/5 * * * *'`

Then it should start on the next 5 minute time slot

**Comment by kjckwok** [comment]
When you edit the config.ini file, the notes asks you to remove the 'initial'. If you are just checking Tesco, then you need to remove the ';' that is before the Tesco_username and Tesco_password. The code will only read those as comments if you don't do this.

**Comment by drakma5** [comment]
Thanks for your replies, removed the necessary initials. However, still running into the same problem of not seeing any output after "yarn start" or "yarn start cron".

**Comment by drakma5** [comment]
solved through replacing files with a fresh download
