### ISSUE TITLE
Failing to launch on Ubuntu 18.04 Droplet 

### ISSUE THREAD

**Issue by dave-hawkins** [paulmaunders/delivery-slot-bot#63]
I apologise if this question shouldn't be asked here. If anyone could spare me a bit of time debugging this so i can set it up for my grandparents i would greatly appreciate it.

I'm trying to run the tool on a DO Droplet and coming across this error every time i hit yarn start

`Error: Failed to launch chrome!
[0501/153807.426413:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.`

It seems that i should be trying to enable `--no-sandbox` somewhere when puppeteer is launched but i'm unsure of where exactly. 

Would anyone be able to point me in the right direction?

**Comment by paulmaunders** [comment]
Try installing it all inside a user account, rather than running as root, e.g.

    useradd deliverybot
    su deliverybot

Then follow the install instructions.

**Comment by dave-hawkins** [comment]
Yup that works, thank you paul!
