### ISSUE TITLE
Install / launch in FreeBSD

### ISSUE THREAD

**Issue by davidone** [paulmaunders/delivery-slot-bot#69]
FreeBSD isn't officially supported by puppeteer so here is what I did to have this project (so helpful right now) running on FreeBSD:
- install puppeteer with PUPPETEER_SKIP_CHROMIUM_DOWNLOAD set to true with:
```
$ PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm install puppeteer
```
- install chromium with an usual:
```
# pkg install chromium
```
- if you have some undefined symbol related to *FT_Palette_Select*, please update FreeType2
- use this trivial patch:
```
diff --git a/src/puppeteer-utils.js b/src/puppeteer-utils.js
index 24bd7ec..012c841 100644
--- a/src/puppeteer-utils.js
+++ b/src/puppeteer-utils.js
@@ -14,10 +14,7 @@ function getBrowser() {
     });
   }
   return puppeteer.launch({
-    executablePath: config.browserExecutablePath,
-    headless: config.browser_launch_headless,
-    // @ts-ignore
-    product: config.browser_product,
+       executablePath: '/usr/local/bin/chrome',
   });
 }
```

Tested with:
- FreeBSD 12.1-RELEASE-p2 GENERIC  amd64
- npm-6.12.1
- puppeteer@3.0.2
- chromium-81.0.4044.129

**Comment by andytson** [comment]
just:
config.ini:
browser_executable_path = /usr/local/bin/chrome

**Comment by davidone** [comment]
The reason was that puppeteer-utils.js couldn't access the config vars but I see that this has been fixed in https://github.com/paulmaunders/delivery-slot-bot/pull/70, really thanks.
