### ISSUE TITLE
Cron job failure due to pushover response not being handled?

### ISSUE THREAD

**Issue by scottri007** [paulmaunders/delivery-slot-bot#77]
e.g.

Tesco delivery Jun 04 - 10 slots:
[
  { start: 2020-06-10T07:00:00.000Z, end: 2020-06-10T08:00:00.000Z },
  { start: 2020-06-10T08:00:00.000Z, end: 2020-06-10T09:00:00.000Z },
  { start: 2020-06-10T09:00:00.000Z, end: 2020-06-10T10:00:00.000Z },
  { start: 2020-06-10T10:00:00.000Z, end: 2020-06-10T11:00:00.000Z },
  { start: 2020-06-10T11:00:00.000Z, end: 2020-06-10T12:00:00.000Z },
  { start: 2020-06-10T12:00:00.000Z, end: 2020-06-10T13:00:00.000Z },
  { start: 2020-06-10T13:00:00.000Z, end: 2020-06-10T14:00:00.000Z },
  { start: 2020-06-10T14:00:00.000Z, end: 2020-06-10T15:00:00.000Z },
  { start: 2020-06-10T15:00:00.000Z, end: 2020-06-10T16:00:00.000Z },
  { start: 2020-06-10T16:00:00.000Z, end: 2020-06-10T17:00:00.000Z },
  { start: 2020-06-10T17:00:00.000Z, end: 2020-06-10T18:00:00.000Z },
  { start: 2020-06-10T18:00:00.000Z, end: 2020-06-10T19:00:00.000Z },
  { start: 2020-06-10T19:00:00.000Z, end: 2020-06-10T20:00:00.000Z },
  { start: 2020-06-10T20:00:00.000Z, end: 2020-06-10T21:00:00.000Z },
  { start: 2020-06-10T21:00:00.000Z, end: 2020-06-10T22:00:00.000Z }
]
C:\Users\richa\delivery-slot-bot\node_modules\pushover-notifications\lib\pushover.js:137
      this.onerror(error, res)
           ^

TypeError: this.onerror is not a function
    at Pushover.errors (C:\Users\richa\delivery-slot-bot\node_modules\pushover-notifications\lib\pushover.js:137:12)
    at IncomingMessage.<anonymous> (C:\Users\richa\delivery-slot-bot\node_modules\pushover-notifications\lib\pushover.js:250:12)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

not sure if its relevant but i'm pushing notifications to 4 people.

**Comment by scottri007** [comment]
thanks for creating this script by the way its brilliant :-)

**Comment by andytson** [comment]
what version of node are you using? I know there was a usual warning if a promise rejection failed without being handled, and it said a future version would quit the app. I've not tried node 13/14 yet though

**Comment by scottri007** [comment]
Node.js v12.16.3.

**Comment by scottri007** [comment]
its intermittent btw after a series of failures its just worked successfully

**Comment by andytson** [comment]
yes, it looks like it's a bug coming from pushover server itself, which the pushover library doesn't handle gracefully without us hooking up an error handler for it. It will still error, just with a different message

**Comment by scottri007** [comment]
Thanks. Is there anyway to keep the cron job running? Restarting it
manually at the moment.

**Comment by paulmaunders** [comment]
I was also getting this error, so I'll give the new code a try! Thanks Andy.
