### ISSUE TITLE
Intermittent

### ISSUE THREAD

**Issue by woodsie6** [paulmaunders/delivery-slot-bot#8]
Hi all,
Great piece of work here and look forward to future changes.
Is it just me or does this work intermittently? (see screenshot)

![Screenshot 2020-03-31 at 14 52 57](https://user-images.githubusercontent.com/62934258/78034276-6a41b580-735f-11ea-92aa-a128b729160f.png)

I'm not sure whether it's the Tesco website or my setup, it would be useful for any guidance to help troubleshooting.
Thanks

**Comment by esticle** [comment]
Ditto to the author - just got my 1st load of slots after a 20h wait!

FWIW I've not seen it only print the epoch timestamp only ever.. usually you'll get a stderr timeout, etc. if it is something else.

I dont know JS but hacked at it and at least got Sainsburys login page.. but looks like it'll captcha after a number of logins...

**Comment by paulmaunders** [comment]
I've just noticed that this afternoon too. I wasn't seeing this before.

```paulmaunders@pauls-air delivery-slot-bot % yarn start
yarn run v1.22.4
$ node delivery-slots.js
1585666728171 Tue, 31 Mar 2020 14:58:48 GMT
✨  Done in 4.28s.
```

I'm not sure what's causing it though at the moment... it could be the server is returning an error or empty page.

**Comment by paulmaunders** [comment]
If I take a screenshot of the delivery page when it fails, it's showing the login page - which would suggest to me there was an issue with the login:

![tesco-delivery-main](https://user-images.githubusercontent.com/245434/78044389-8730b580-736c-11ea-8f7b-49b4ae6982fb.png)

**Comment by paulmaunders** [comment]
Mine has worked today. It alerted me to a slot and I managed to book a delivery woohoo

**Comment by andytson** [comment]
@esticle you might get further information in the latest update if you
```
git pull origin master
yarn install
```
