### ISSUE TITLE
Tesco have added a queue system now it seems :(

### ISSUE THREAD

**Issue by MrDibbley** [paulmaunders/delivery-slot-bot#83]
You're now in a queue to shop with us. Please keep this page open – it will refresh automatically.

need a bit of logic to sit and wait now somehow.....

Thanks

**Comment by git-creat** [comment]
They have had a queuing system for the last few months, when they used to release all the slots at midnight if you went on at around 2340 you would have to wait in a 20-30 minute queue to access the site, I guess it must be an automatic thing that kicks in when traffic on the site is too heavy as it's not there all the time, Boots have one on almost all the time.

**Comment by MrDibbley** [comment]
ok cool thanks
