### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by HennahS-ALTOUR** [paulmaunders/delivery-slot-bot#9]
Please can someone help me with the usage steps?

**Comment by paulmaunders** [comment]
Hi Hennah, if you have the latest version you can just run `yarn start` from within the project folder. If you're using an older version try running `node delivery-slots.js`. This assumes you've already added all your Tesco account settings in the config.ini file

**Comment by HennahS-ALTOUR** [comment]
Hi Paul, if I use `node delivery-slots.js` does that mean the code will not be scheduled to execute every so often using the internal cron schedule?

The issue I'm facing is any yarn command is not found..
`-bash: yarn: command not found`
